ControleEstoque.Web/Controllers/Cadastro/CadastroGrupoProdutoController.cs
using ControleEstoque.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers
{
    [Authorize(Roles = "Gerente, Administrativo, Operador")]
    public class CadastroGrupoProdutoController : Controller
    {
        private const int _maxLinhasPorPagina = 6;


        
        // public ActionResult ObterGrupoProduto()
        public ActionResult Index()
        {
            ViewBag.ListaTamPag = new SelectList(new int[] { _maxLinhasPorPagina, 10, 15, 20, 30 }, _maxLinhasPorPagina);
            ViewBag.MaxLinhasPorPagina = _maxLinhasPorPagina;
            ViewBag.PaginaAtual = 1;

            var lista = GrupoProdutoModel.Obter(ViewBag.PaginaAtual, _maxLinhasPorPagina);
            var quantidade = GrupoProdutoModel.ObterQuantidade();


            ViewBag.QuantPaginas = (quantidade / ViewBag.MaxLinhasPorPagina);
            if ((quantidade % ViewBag.MaxLinhasPorPagina) > 0)
                ViewBag.QuantPaginas += 1;

            return View(lista);
        }

        
        
        public JsonResult ObterGrupoProdutoGrid(int pagina, int tamPag)
        {
            var lista = GrupoProdutoModel.Obter(pagina, tamPag);

            return Json(lista);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ObterGrupoProdutoId(int id)
        {
            return Json(GrupoProdutoModel.ObterId(id));
        }

        [HttpPost]
        [Authorize(Roles = "Gerente")]
        [ValidateAntiForgeryToken]
        public JsonResult ExcluirGrupoProdutoId(int id)
        {
            return Json(GrupoProdutoModel.ExcluirId(id));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult SalvarGrupoProduto(GrupoProdutoModel model)
        {
            var resultado = "Ok";
            var mensagens = new List<string>();
            var idSalvo = string.Empty;

            if (!ModelState.IsValid)
            {
                resultado = "Aviso";
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    var id = model.Salvar();
                    if (id > 0)
                    {
                        idSalvo = id.ToString();
                    }
                    else
                    {
                        resultado = "Erro";
                    }
                }
                catch (Exception ex)
                {
                    resultado = "Erro";
                }
            }

            return Json(new { Resultado = resultado, Mensagens = mensagens, IdSalvo = idSalvo });
        }
    }
}

ControleEstoque.Web/Controllers/Cadastro/CadastroUnidadeMedidaController.cs
using ControleEstoque.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers
{
    public class CadastroUnidadeMedidaController : Controller
    {
        private const int _maxLinhasPorPagina = 6;


        [Authorize]
        // public ActionResult ObterUnidadeMedida()
        public ActionResult Index()
        {
            ViewBag.ListaTamPag = new SelectList(new int[] { _maxLinhasPorPagina, 10, 15, 20, 30 }, _maxLinhasPorPagina);
            ViewBag.MaxLinhasPorPagina = _maxLinhasPorPagina;
            ViewBag.PaginaAtual = 1;

            var lista = UnidadeMedidaModel.Obter(ViewBag.PaginaAtual, _maxLinhasPorPagina);
            var quantidade = UnidadeMedidaModel.ObterQuantidade();


            ViewBag.QuantPaginas = (quantidade / ViewBag.MaxLinhasPorPagina);
            if ((quantidade % ViewBag.MaxLinhasPorPagina) > 0)
                ViewBag.QuantPaginas += 1;

            return View(lista);
        }

        [Authorize]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult ObterUnidadeMedidaGrid(int pagina, int tamPag)
        {
            var lista = UnidadeMedidaModel.Obter(pagina, tamPag);

            return Json(lista);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult ObterUnidadeMedidaId(int id)
        {
            return Json(UnidadeMedidaModel.ObterId(id));
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult ExcluirUnidadeMedidaId(int id)
        {
            return Json(UnidadeMedidaModel.ExcluirId(id));
        }


        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult SalvarUnidadeMedida(UnidadeMedidaModel model)
        {
            var resultado = "Ok";
            var mensagens = new List<string>();
            var idSalvo = string.Empty;

            if (!ModelState.IsValid)
            {
                resultado = "Aviso";
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    var id = model.Salvar();
                    if (id > 0)
                    {
                        idSalvo = id.ToString();
                    }
                    else
                    {
                        resultado = "Erro";
                    }
                }
                catch (Exception ex)
                {
                    resultado = "Erro";
                }
            }

            return Json(new { Resultado = resultado, Mensagens = mensagens, IdSalvo = idSalvo });
        }
    }
}

ControleEstoque.Web/Controllers/Cadastro/CadastroUsuarioController.cs
using ControleEstoque.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers
{
    public class CadastroUsuarioController : Controller
    {
       
        //Senha padrão para alteração de usuário sem senha
        //Permitir a regra de negocio
        private const string _senhaPadrao = "{$127;$188}";
        
        private const int _maxLinhasPorPagina = 6;

        [Authorize]
        public ActionResult Index()
        {
            ViewBag.SenhaPadrao = _senhaPadrao;
            
            ViewBag.ListaTamPag = new SelectList(new int[] { _maxLinhasPorPagina, 10, 15, 20, 30 }, _maxLinhasPorPagina);
            ViewBag.MaxLinhasPorPagina = _maxLinhasPorPagina;
            ViewBag.PaginaAtual = 1;

            var lista = UsuarioModel.Obter(ViewBag.PaginaAtual, _maxLinhasPorPagina);
            var quantidade = UsuarioModel.ObterQuantidade();


            ViewBag.QuantPaginas = (quantidade / ViewBag.MaxLinhasPorPagina);
            if ((quantidade % ViewBag.MaxLinhasPorPagina) > 0)
                ViewBag.QuantPaginas += 1;

            return View(lista);
        }


        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult ObterUsuarioId(int id)
        {
            return Json(UsuarioModel.ObterId(id));
        }

        [Authorize]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult ObterUsuarioGrid(int pagina, int tamPag)
        {
            var lista = UsuarioModel.Obter(pagina, tamPag);

            return Json(lista);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult ExcluirUsuarioId(int id)
        {
            return Json(UsuarioModel.ExcluirId(id));
        }


        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult SalvarUsuario(UsuarioModel model)
        {
            var resultado = "Ok";
            var mensagens = new List<string>();
            var idSalvo = string.Empty;

            if (!ModelState.IsValid)
            {
                resultado = "Aviso";
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    //Alteração de usuário sem setar senha
                    if (model.Senha == _senhaPadrao)
                        model.Senha = "";

                    var id = model.Salvar();
                    if (id > 0)
                    {
                        idSalvo = id.ToString();
                    }
                    else
                    {
                        resultado = "Erro";
                    }
                }
                catch (Exception ex)
                {
                    resultado = "Erro";
                }
            }

            return Json(new { Resultado = resultado, Mensagens = mensagens, IdSalvo = idSalvo });
        }
    }
}

ControleEstoque.Web/Controllers/CadastroController.cs
using ControleEstoque.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers
{
    public class CadastroController : Controller
    {

        private const int _maxLinhasPorPagina = 6;

       

        [Authorize]
        public ActionResult MarcaProduto()
        {
            return View();
        }
        [Authorize]
        public ActionResult LocalProduto()
        {
            return View();
        }
        [Authorize]
        public ActionResult UnidadeMedida()
        {
            return View();
        }
        [Authorize]
        public ActionResult Cidade()
        {
            return View();
        }
        [Authorize]
        public ActionResult Produto()
        {
            return View();
        }
        [Authorize]
        public ActionResult Pais()
        {
            return View();
        }
        [Authorize]
        public ActionResult Estado()
        {
            return View();
        }
        [Authorize]
        public ActionResult Fornecedor()
        {
            return View();
        }
        [Authorize]
        public ActionResult PerfilUsuario()
        {
            return View();
        }

    }
}

ControleEstoque.Web/Controllers/ContaController.cs
using ControleEstoque.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;

namespace ControleEstoque.Web.Controllers
{
    public class ContaController : Controller
    {


        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }


        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(LoginViewModel login, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(login);
            }

            var usuario = (UsuarioModel.ValidarUsuario(login.Usuario, login.Senha));
            if (usuario != null)
            {
                //FormsAuthentication.SetAuthCookie(usuario.Nome, login.LembrarMe);
                var ticket = FormsAuthentication.Encrypt(new FormsAuthenticationTicket(
                    1, usuario.Nome, DateTime.Now, DateTime.Now.AddMinutes(15), login.LembrarMe, "Gerente"));
                var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, ticket);

                Response.Cookies.Add(cookie);

                if (Url.IsLocalUrl(returnUrl))
                {
                    return Redirect(returnUrl);

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                ModelState.AddModelError("", "Login Inválido.");
            }

            return View(login);
        }
        [HttpPost]
        [AllowAnonymous]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

ControleEstoque.Web/Controllers/GraficoController.cs
using ControleEstoque.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers
{
    public class GraficoController : Controller
    {
        [Authorize]
        public ActionResult PerdaMes()
        {
            return View();
        }
        [Authorize]
        public ActionResult EntradaSaidaMes()
        {
            return View();
        }
    }
}

ControleEstoque.Web/Controllers/OperacaoController.cs
using ControleEstoque.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers
{
    public class OperacaoController : Controller
    {
        [Authorize]
        public ActionResult EntradaEstoque()
        {
            return View();
        }
        [Authorize]
        public ActionResult SaidaEstoque()
        {
            return View();
        }
        [Authorize]
        public ActionResult LancPerdaProduto()
        {
            return View();
        }
        [Authorize]
        public ActionResult Inventario()
        {
            return View();
        }
    }
}

ControleEstoque.Web/Controllers/RelatorioController.cs
using ControleEstoque.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers
{
    public class RelatorioController : Controller
    {
        [Authorize]
        public ActionResult PosicaoEstoque()
        {
            return View();
        }
        [Authorize]
        public ActionResult Ressuprimento()
        {
            return View();
        }
    }
}

ControleEstoque.Web/Views/Shared/_Cadastro.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@RenderSection("Styles", true)
@RenderBody()


<div id="cadastro">
    <section id="cadastro_cabecalho">
        <h1>@ViewBag.Title</h1>
    </section>
    <section id="cadastro_conteudo">
        <div id="grid_cabecalho" class="row">
            <div class="col-md-12">
                <a id="btn_incluir" class="btn btn-success" role="button"><i class="glyphicon glyphicon-plus"></i> Incluir</a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <table id="grid_cadastro" class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            @RenderSection("TituloGrid", true)
                        </tr>
                    </thead>
                    <tbody>
                        @RenderSection("LinhaGrid", true)
                    </tbody>
                </table>
            </div>
        </div>
        @if (ViewBag.QuantPaginas > 1)
        {
            <div id="grid_paginacao" class="row">
                <div class="col-md-12">
                    <div class="col-md-6">
                        <nav aria-label="Navegação">
                            <ul class="pagination justify-content-end">
                                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                @for (int i = 2; i <= ViewBag.QuantPaginas; i++)
                                {
                                    <li class="page-item"><a class="page-link" href="#">@i</a></li>
                                }

                            </ul>
                        </nav>
                    </div>
                    <div class="col-md-6" style="float:right">
                        @Html.Label("Elementos na página", null, new { @class = "" })
                        @Html.DropDownList("ddl_tam_pag", (SelectList)ViewBag.ListaTamPag, new { @class = "selectpicker" })
                    </div>
                </div>
            </div>
        }
    </section>
</div>

<div id="modal_cadastro" class="form-horizontal invisivel" role="dialog">
    <div id="msg_mensagem_aviso" class="text-danger invisivel"></div>
    <fieldset>
        @Html.AntiForgeryToken()
        @RenderSection("CamposCadastro", true)

        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="modal-footer">
                        <a id="btn_sair" class="btn btn-default" role="button" data-dismiss="modal"><i class="glyphicon glyphicon-remove"></i> Sair</a>
                        <a id="btn_confirmar" class="btn btn-primary" role="button"><i class="glyphicon glyphicon-ok"></i> Salvar</a>
                    </div>
                    <div id="msg_aviso" class="alert alert-warning invisivel">Falta preencher os campos acima.</div>
                    <div id="msg_erro" class="alert alert-danger invisivel">Opa!! Deu ruim.</div>
                </div>
            </div>
        </div>
    </fieldset>
</div>

@Html.Hidden("id_cadastro")

@section Scripts{
    @RenderSection("Scripts", true)
    <script src="~/Scripts/Cadastro/CadastroBase.js"></script>
}

ControleEstoque.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Controle de Estoque</title>
    <link rel="shortcut icon" href="~/Images/ibama.ico" type="image/x-icon"/>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <img src="~/Images/Logo_IBAMA.svg.png" style="float:left" width="5%" />
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(" Controle de Estoque", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cadastros<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Grupos de Produtos", "Index", "CadastroGrupoProduto")</li>
                                <li>@Html.ActionLink("Marcas de Produtos", "MarcaProduto", "Cadastro")</li>
                                <li>@Html.ActionLink("Locais de Armazenamento", "LocalProduto", "Cadastro")</li>
                                <li>@Html.ActionLink("Unidades de medida", "Index", "CadastroUnidadeMedida")</li>
                                <li>@Html.ActionLink("Produtos", "Produto", "Cadastro")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Países", "Pais", "Cadastro")</li>
                                <li>@Html.ActionLink("Estados", "Estado", "Cadastro")</li>
                                <li>@Html.ActionLink("Cidades", "Cidade", "Cadastro")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Fornecedores", "Fornecedor", "Cadastro")</li>
                                <li>@Html.ActionLink("Perfis de usuário", "PerfilUsuario", "Cadastro")</li>
                                <li>@Html.ActionLink("Usuários", "Index", "CadastroUsuario")</li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Operações<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Entrada de Produtos", "EntradaEstoque", "Operacao")</li>
                                <li>@Html.ActionLink("Saída de Produtos", "SaidaEstoque", "Operacao")</li>
                                <li>@Html.ActionLink("Lançamento de perdas de produtos", "LancPerdaProduto", "Operacao")</li>
                                <li>@Html.ActionLink("Inventário de Estoque", "Inventario", "Operacao")</li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Relatórios<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Posição do Estoque", "PosicaoEstoque", "Relatorio")</li>
                                <li>@Html.ActionLink("Ressuprimento", "Ressuprimento", "Relatorio")</li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Gráficos<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Perdas por mês", "PerdaMes", "Grafico")</li>
                                <li>@Html.ActionLink("Entradas x Saídas por mês", "EntradaSaidaMes", "Grafico")</li>
                            </ul>
                        </li>
                    </ul>
                    using (Html.BeginForm("LogOff", "Conta", FormMethod.Post, new { id = "logoffForm" }))
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("Sobre", "Sobre", "Home")</li>
                            <li><a href="#">Olá @User.Identity.Name</a></li>
                            
                            <li>
                                @*<li class="navbar-btn">*@
                                @*<input type="submit" class="btn btn-info" value="Sair" />*@
                                <a href="javascript:document.getElementById('logoffForm').submit()">Sair</a>
                            </li>

                        </ul>
                    }
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        @*<li>@Html.ActionLink("Login", "Login", "Conta")</li>*@
                        <li>@Html.ActionLink("Sobre", "Sobre", "Home")</li>
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Controle de Estoque</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>